import Layout from "@/components/Layout"
import Head from "next/head"
import { Typography } from "antd"
import TaskList from "@/components/TaskList"

const { Title } = Typography

export default function Home() {
    return (
        <>
            <Head>
                <title>Personal Task Manager</title>
                <meta
                    name="Personal Task Manager"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <Layout>
                    <div>
                        <Title level={4}>Task List</Title>
                        <TaskList />
                    </div>
                </Layout>
            </main>
        </>
    )
}
