import Head from "next/head"

export default function Home() {
    return (
        <>
            <Head>
                <title>Personal Task Manager</title>
                <meta
                    name="Personal Task Manager"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>Homepage</main>
        </>
    )
}
